networks:
  grafana:

volumes:
  app_data: {}
  etl_logs: {}

services:
  prometheus:
    image: prom/prometheus:v2.49.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  grafana:
    image: grafana/grafana:12.0.1
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # grants admin role to anonymous access
      - GF_AUTH_ANONYMOUS_ENABLED=true # removes login 1/2
      - GF_AUTH_BASIC_ENABLED=false # removes login 2/2
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting

  app:
    build: ./app
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    ports:
      - 8082:80
    networks:
      - grafana

  etl-simulator:
    build:
      context: ./etl
      dockerfile: Dockerfile.etl
    container_name: etl-simulator
    networks:
      - grafana
    volumes:
      - etl_logs:/app/logs
    working_dir: /app
    command: python3 etl_simulator.py
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_FILE=/app/logs/etl_process.log
    healthcheck:
      test: ["CMD", "python3", "-c", "import os; exit(0 if os.path.exists('/app/logs/etl_process.log') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3

  etl-metrics:
    build:
      context: ./etl
      dockerfile: Dockerfile.etl
    container_name: etl-metrics
    networks:
      - grafana
    ports:
      - "8083:8083"
    volumes:
      - etl_logs:/app/logs
    working_dir: /app
    command: python3 metrics_exporter.py
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_FILE=/app/logs/etl_process.log
    depends_on:
      - etl-simulator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3