groups:
  - name: etl_alerts
    folder: ETL Monitoring
    interval: 30s
    rules:
      - uid: etl_health_down
        title: ETL Process Health Check Failed
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: etl_health_status
              interval: ''
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: "${B} < 1"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: math
        noDataState: Alerting
        execErrState: Alerting
        for: 2m
        annotations:
          summary: ETL process health check is failing
          description: 'The ETL process health status has been 0 (down) for more than 2 minutes. This indicates the ETL process may have stopped or is not processing files.'
        labels:
          severity: critical
          team: data-engineering
          service: etl

      - uid: etl_no_success_10min_v2
        title: No ETL Success in 10 Minutes
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: etl_seconds_since_last_success
              interval: ''
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: "${B} > 600"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: math
        noDataState: Alerting
        execErrState: Alerting
        for: 1m
        annotations:
          summary: No successful ETL file processing in over 10 minutes
          description: 'ETL has not successfully processed any files in over 10 minutes. Expected frequency is approximately every 1-5 minutes.'
        labels:
          severity: warning
          team: data-engineering
          service: etl

      - uid: etl_high_failure_rate_v2
        title: High ETL Failure Rate
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: increase(etl_failures_total[5m])
              interval: ''
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: "${B} > 3"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: math
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          summary: High ETL failure rate detected
          description: 'ETL process has experienced an unusually high number of failures in the last 5 minutes. Normal rate is approximately 1 failure per minute.'
        labels:
          severity: warning
          team: data-engineering
          service: etl

      - uid: etl_low_throughput_v2
        title: ETL Processing Rate Below Threshold
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: rate(etl_records_total[5m]) * 60
              interval: ''
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: "${B} < 100"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: math
        noDataState: Alerting
        execErrState: Alerting
        for: 3m
        annotations:
          summary: ETL processing rate is below expected threshold
          description: 'Current ETL processing rate has fallen below the expected threshold of 100 records per minute. Expected normal rate is approximately 600 records per minute.'
        labels:
          severity: warning
          team: data-engineering
          service: etl

      - uid: etl_excessive_processing_time_v2
        title: ETL Average Processing Time Too High
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: etl_avg_processing_time_seconds
              interval: ''
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: "${B} > 5"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: math
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          summary: ETL average processing time is unusually high
          description: 'ETL average processing time has exceeded 5 seconds per file, which may indicate performance issues or larger than normal files.'
        labels:
          severity: warning
          team: data-engineering
          service: etl

      - uid: etl_metrics_endpoint_down
        title: ETL Metrics Endpoint Unavailable
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 120
              to: 0
            datasourceUid: prometheus
            model:
              expr: up{job="etl_metrics"}
              interval: ''
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: "${B} < 1"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: math
        noDataState: Alerting
        execErrState: Alerting
        for: 1m
        annotations:
          summary: ETL metrics endpoint is not responding
          description: 'The ETL metrics exporter endpoint is down or unreachable. This will prevent monitoring of the ETL process.'
        labels:
          severity: critical
          team: data-engineering
          service: etl