apiVersion: 1

policies:
  - orgId: 1
    receiver: etl-alerts
    group_by: ['grafana_folder', 'alertname']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    routes:
      - receiver: etl-alerts
        matchers:
          - service = etl
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 30m
      - receiver: etl-alerts
        matchers:
          - severity = critical
        group_wait: 5s
        group_interval: 2m
        repeat_interval: 15m

contactPoints:
  - orgId: 1
    name: etl-alerts
    receivers:
      - uid: etl_email_uid
        type: email
        settings:
          addresses: srmitin@yahoo.com
          subject: 'ETL Monitoring Alert: {{ .CommonLabels.alertname }}'
          html: true
          message: |
            ETL MONITORING ALERT
            ====================
            
            Alert: {{ .CommonLabels.alertname }}
            Severity: {{ .CommonLabels.severity }}
            Status: {{ .Status }}
            Service: {{ .CommonLabels.service }}
            Team: {{ .CommonLabels.team }}
            
            ALERT DETAILS:
            {{ range .Alerts }}
            --------------
            Summary: {{ .Annotations.summary }}
            Description: {{ .Annotations.description }}
            Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}{{ if .EndsAt }}
            Ended: {{ .EndsAt.Format "2006-01-02 15:04:05 UTC" }}{{ end }}
            
            Labels:
            {{ range .Labels.SortedPairs }}  - {{ .Name }}: {{ .Value }}
            {{ end }}
            {{ end }}
            
            Generated by ETL Monitoring System
            Dashboard: http://localhost:3000/d/etl-monitoring
        disableResolveMessage: false
      - uid: etl_webhook_uid
        type: webhook
        settings:
          url: http://etl-metrics:8083/alerts
          httpMethod: POST
          maxAlerts: 10
          title: 'ETL Alert: {{ .CommonLabels.alertname }}'
          message: |
            {
              "alert_name": "{{ range .Alerts }}{{ .Labels.alertname }}{{ break }}{{ end }}",
              "severity": "{{ range .Alerts }}{{ .Labels.severity }}{{ break }}{{ end }}",
              "service": "{{ range .Alerts }}{{ .Labels.service }}{{ break }}{{ end }}",
              "team": "{{ range .Alerts }}{{ .Labels.team }}{{ break }}{{ end }}",
              "status": "{{ .Status }}",
              "alert_count": {{ len .Alerts }},
              "summary": "{{ range .Alerts }}{{ .Annotations.summary }}{{ break }}{{ end }}",
              "description": "{{ range .Alerts }}{{ .Annotations.description }}{{ break }}{{ end }}"
            }
        disableResolveMessage: false

templates: []