apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_ADMIN_PASSWORD}
    isDefault: true
    editable: true
  - name: TestData
    type: testdata
    access: proxy
    orgId: 1
  - name: PrometheusDirect
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus_direct
    url: http://host.docker.internal:8000
    basicAuth: false
    isDefault: false
    editable: true
